pull_request_rules:
  - name: merge on CI success and 2 approvals
    conditions:
      - 'status-success=ci/circleci: comit-build'
      - "#approved-reviews-by>=2"
      - label!=work-in-progress
      - label!=blocked
      - label=automagically-mergify-this
      - "#changes-requested-reviews-by=0"
    actions:
      merge:
        method: merge
        strict: smart
        strict_method: rebase
      delete_head_branch:
