[workspace]

members = [
    "application/comit_node",
    "application/ledger_query_service",
    "vendor/bam",
    "vendor/bitcoin_rpc_test_helpers",
    "vendor/bitcoin_support",
    "vendor/bitcoin_witness",
    "vendor/ethereum_support",
    "vendor/key_gen",
    "vendor/secp256k1_support",
    "vendor/tc_bitcoincore_client",
    "vendor/tc_web3_client",
    "vendor/noise_handshake"
]

[replace]
"bitcoin_rpc_client:0.5.0" = { git = "https://github.com/coblox/bitcoinrpc-rust-client", branch = "from-verboserawtx-to-bitcointx" }
